[en]
title = "Palatino"
context = "Georgia"
math = "Times New Roman"

[zh]
title = "STKaiti"
context = "Songti SC"
math = "Kaiti SC"

[th]
title = "Chulabhorn Likit Display"
context = "Chulabhorn Likit Text"
math = "TH Sarabun Chula"
